name: Playwright Containerized Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  playwright:
    name: 'Playwright Containerized Tests'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    container:
      image: mcr.microsoft.com/playwright:v1.42.1-jammy
    steps:
      - uses: actions/checkout@v4
      - name: Install package manager
        run: |
          corepack enable
          yarn --version
          yarn config set npmScopes.my-org.npmRegistryServer "https://npm.pkg.github.com"
          yarn config set npmScopes.my-org.npmAlwaysAuth true
          yarn config set npmScopes.my-org.npmAuthToken $NPM_AUTH_TOKEN
          yarn config set cacheFolder './.yarn/cache'
          yarn config set nodeLinker node-modules
          yarn config set enableTelemetry false
          yarn config set enableGlobalCache false
          yarn config set enableMirror true
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: |
            ./yarn.lock
            ./package.json
            ./.yarnrc.yml
      - name: install dependencies
        run: yarn
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run your tests
        run: yarn dlx playwright test
        env:
          HOME: /root
