name: Playwright Deployment Tests
on:
  deployment_status:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'
    steps:
      - uses: actions/checkout@v4
      - name: Install package manager
        run: |
          corepack enable
          yarn --version
          yarn config set npmScopes.my-org.npmRegistryServer "https://npm.pkg.github.com"
          yarn config set npmScopes.my-org.npmAlwaysAuth true
          yarn config set npmScopes.my-org.npmAuthToken $NPM_AUTH_TOKEN
          yarn config set cacheFolder './.yarn/cache'
          yarn config set nodeLinker node-modules
          yarn config set enableTelemetry false
          yarn config set enableGlobalCache false
          yarn config set enableMirror true
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: |
            ./yarn.lock
            ./package.json
            ./.yarnrc.yml
      - name: install dependencies
        run: yarn
      - name: Install Playwright
        run: yarn dlx playwright install --with-deps
      - name: Run Playwright tests
        run: yarn dlx playwright test
        env:
          PLAYWRIGHT_TEST_BASE_URL: ${{ github.event.deployment_status.target_url }}
