name: Playwright e2e Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install package manager
        run: corepack enable
      - name: print package manager version
        run: yarn --version
      - name: configure package manager
        run: |
          yarn config set npmScopes.my-org.npmRegistryServer "https://npm.pkg.github.com"
          yarn config set npmScopes.my-org.npmAlwaysAuth true
          yarn config set npmScopes.my-org.npmAuthToken $NPM_AUTH_TOKEN
          yarn config set cacheFolder ./.yarn/cache
          yarn config set nodeLinker node-modules
          yarn config set enableTelemetry false
          yarn config set enableGlobalCache false
          yarn config set ignorePath true
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: |
            ./yarn.lock
            ./package.json
            ./.yarnrc.yml
      - name: install dependencies
        run: yarn
        
      - name: Install Playwright Browsers
        run: yarn dlx playwright install --with-deps
      - name: Run Playwright tests
        run: yarn dlx playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30  
