name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    permissions:
      contents: read
      actions: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install package manager
      run: corepack enable
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: yarn
        cache-dependency-path: |
          ./yarn.lock
          ./package.json
          ./.yarnrc.yml
    - name: Setup .yarnrc.yml
      run: |
        yarn config set npmScopes.my-org.npmRegistryServer "https://npm.pkg.github.com"
        yarn config set npmScopes.my-org.npmAlwaysAuth true
        yarn config set npmScopes.my-org.npmAuthToken $NPM_AUTH_TOKEN
        yarn config set cacheFolder './.yarn/cache'
        yarn config set nodeLinker node-modules
        yarn config set enableTelemetry false
        yarn config set enableGlobalCache false
        yarn config set enableMirror true
      env:
        NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install dependencies
      run: yarn
    - name: check types
      run: yarn typecheck
    - name: Setup Biome
      uses: biomejs/setup-biome@v2
      with:
        version: latest
    - name: Run Biome
      run: biome ci .
    - name: build to publish
      run: yarn build
